### ISSUE TITLE
isInitialRoute error

### ISSUE THREAD

**Issue by hemguna** [TheAlphamerc/flutter_ecommerce_app#2]
The getter 'isInitialRoute' isn't defined for the type 'RouteSettings'.
Try importing the library that defines 'isInitialRoute', correcting the name to the name of an existing getter, or defining a getter or field named 'isInitialRoute'.

<img width="960" alt="error" src="https://user-images.githubusercontent.com/15955088/81612648-c84fc700-93fa-11ea-8d78-956a3d4c7ed0.png">

**Comment by lwluck** [comment]
From https://flutter.dev/docs/release/breaking-changes/route-navigator-refactoring
> Finally, we removed the isInitialRoute property from RouteSetting as part of refactoring, and provided the onGenerateInitialRoutes API for full control of initial routes generation.

There is a migration guide on that page as well. I will have a PR up shortly which I believe fixes it and cleans up some naming issues I noticed, but the below seems to work.

### main.dart
``` dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'E-Commerce ',
      theme: AppTheme.lightTheme.copyWith(
        textTheme: GoogleFonts.muliTextTheme(
          Theme.of(context).textTheme,
        ),
      ),
      debugShowCheckedModeBanner: false,
      routes: Routes.getRoute(),
      onGenerateRoute: (RouteSettings settings) {
        if (settings.name.contains('detail')) {
          return CustomRoute<bool>(
              builder: (BuildContext context) => ProductDetailPage());
        } else {
          return CustomRoute<bool>(
              builder: (BuildContext context) => MainPage());
        }
      },
      initialRoute: "MainPage",
    );
  }
}
```
### customRoute.dart
``` dart
class CustomRoute<T> extends MaterialPageRoute<T> {
  CustomRoute({WidgetBuilder builder, RouteSettings settings})
      : super(builder: builder, settings: settings);
  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    if (settings.name == "MainPage") {
      return child;
    }
    return FadeTransition(
      opacity: animation,
      child: child,
    );
  }
}
```
