### ISSUE TITLE
Backend feature

### ISSUE THREAD

**Issue by ublockme** [TheAlphamerc/flutter_ecommerce_app#21]
Really lovely ui.. When will you add backend coding?

**Comment by GerhardMes** [comment]
great idea.

**Comment by ublockme** [comment]
@GerhardMes yes, it will be great app if added backend..

**Comment by TheAlphamerc** [comment]
Adding backend will be good when we have a enough ui/ux for app with a flow of data and currently we didn't have these so we are waiting for those.

**Comment by ublockme** [comment]
We also waiting 😊👍
All the best for next projects
