### ISSUE TITLE
Unresolved class 'MainActivity'

### ISSUE THREAD

**Issue by VishalDhanasek** [TheAlphamerc/flutter_ecommerce_app#22]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/54840593/122706843-65279980-d276-11eb-8a4b-9fa84403f24f.PNG">

**Comment by TheAlphamerc** [comment]
Can you share exact error you are getting. I am not able to see it in shared screenshot.

**Comment by VishalDhanasek** [comment]
Sure

**Comment by VishalDhanasek** [comment]
![20210621_103237](https://user-images.githubusercontent.com/54840593/122709934-e2eea380-d27c-11eb-955f-e5601cf2c1f1.jpg)
<img width="841" alt="error2" src="https://user-images.githubusercontent.com/54840593/122709948-e8e48480-d27c-11eb-8cc6-b4dfba5d3d4d.PNG">

**Comment by TheAlphamerc** [comment]
Try  `flutter clean` and `flutter pub get` command.

**Comment by VishalDhanasek** [comment]
I tried but it doesn't work

**Comment by TheAlphamerc** [comment]
Can you try it in vs-code ?

**Comment by VishalDhanasek** [comment]
Sure let me try
