### ISSUE TITLE
Execution failed for task ':app:processDebugResources'.

### ISSUE THREAD

**Issue by Tareque2208** [TheAlphamerc/flutter_ecommerce_app#23]
**Describe the bug**
     After installing package while trying to run in emulator It gives this error message.
     
     FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     I:\Flutter\flutter_ecommerce_app-master\android\app\src\main\res\drawable\launch_background.xml:13: AAPT: error: resource drawable/ic_launcher (aka com.thealphamerc.flutter_ecommerce_app:drawable/ic_launcher) not found.
     I:\Flutter\flutter_ecommerce_app-master\android\app\src\main\res\drawable-v21\launch_background.xml:13: AAPT: error: resource drawable/ic_launcher (aka com.thealphamerc.flutter_ecommerce_app:drawable/ic_launcher) not found.
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org

The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
[!] Flutter tried to create the file `android\settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:
    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:
        def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
        def properties = new Properties()
        assert localPropertiesFile.exists()
        localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
Exception: Please create the file and run this command again.

![2021-08-26 10_19_50-Window](https://user-images.githubusercontent.com/16764227/130900048-5154f164-7fff-405c-be05-08236be0e6d9.png)

**Comment by TheAlphamerc** [comment]
@Tareque2208 issue is fixed. let me know if you face any other issue.

**Comment by Tareque2208** [comment]
Amazing brother. Thank you. I already fixed the issue in my local pc and ran perfectly.
