### ISSUE TITLE
Android Studio Issue

### ISSUE THREAD

**Issue by tommyready** [TheAlphamerc/flutter_ecommerce_app#4]
When I open this project in Android Studio is see this issue in Windows 10. Guess I should mention I am new to Flutter and Dart.
![image](https://user-images.githubusercontent.com/597594/82348034-58c37400-99c6-11ea-94b9-6599672f72b2.png)

**Comment by TheAlphamerc** [comment]
@tommyready issue is fixed. The issue is causing due to the lower version of the dart. 
https://github.com/Dart-Code/Dart-Code/issues/2253#issue-562205826
