### ISSUE TITLE
Where the server to proccess ceckout customer??

### ISSUE THREAD

**Issue by hendriksinaga13** [TheAlphamerc/flutter_ecommerce_app#5]
hello dear, have you that web app for this?? or whre the server if we processing customer checkout??

**Comment by TheAlphamerc** [comment]
Hi @hendriksinaga13, Currently backend part is not developed yet. I am planning to integrate the firebase as backend soon.

**Comment by hendriksinaga13** [comment]
Ok bro, i wait  your update
Thank you very much

**Comment by zhex900** [comment]
Hi, 

How about make this backend agnostic? Like [vue store front](https://docs.vuestorefront.io/guide/). This app can be a headless ecommerce frontend. This way you can connect any backend shop to it. 

Take the same idea as Vue Store Front. Implement API data/connector layer, that have fixed endpoints, like checkout, login, create order, payment. To use other backend shop like Shopify, Bigcommerce, Woocommerce ... you just need to implement a connector for those shops. 

What do you think?

Jake
