### ISSUE TITLE
Adding new icon makes background curve out of sync

### ISSUE THREAD

**Issue by klodha** [TheAlphamerc/flutter_ecommerce_app#6]
**Describe the bug**
When trying to add a new element in bottom navigation with index 4, Visual white curved background no longer stay in sync with elevated icons. It seems that 

**To Reproduce**
1. In bottom_navigation_bar, go to line 168
2. add another instance of _icon with index 4. 
3. Run app
4. White curved white bar which move with elastic effect no longer remains behind the selected icon. 

**Expected behavior**
Curved background should dynamically adjust based on number of elements in bottom tabs.

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9
 - OS: Android 10

**Comment by shivanigupta19** [comment]
> **Describe the bug**
> When trying to add a new element in bottom navigation with index 4, Visual white curved background no longer stay in sync with elevated icons. It seems that
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. In bottom_navigation_bar, go to line 168
> 2. add another instance of _icon with index 4.
> 3. Run app
> 4. White curved white bar which move with elastic effect no longer remains behind the selected icon.
> 
> **Expected behavior**
> Curved background should dynamically adjust based on number of elements in bottom tabs.
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Samsung Note 9
> * OS: Android 10

Please attach the image of the issue.

**Comment by TheAlphamerc** [comment]
Closing issue due to no response from @klodha . If someone facing the same issue feel free to reopen the issue.
