### ISSUE TITLE
A RenderFlex overflowed by 2.3 pixels on the bottom.

### ISSUE THREAD

**Issue by tenSunFree** [TheAlphamerc/flutter_ecommerce_app#7]
**Describe the bug**
A RenderFlex overflowed by 2.3 pixels on the bottom.
![2020-07-29_003930](https://user-images.githubusercontent.com/23090085/88695242-30799380-d134-11ea-8e23-6f7fc9661fa4.jpg)
![Screenshot_20200729-001506](https://user-images.githubusercontent.com/23090085/88695272-3c655580-d134-11ea-8b1f-fa9ddd09e46e.png)

**Smartphone (please complete the following information):**
 - Device: HTC U11
 - OS: Android 9

I added a semi-transparent black background for the picture. You can find that the background heights of the two pictures are different, which may cause errors in phones of different sizes.
![Screenshot_20200729-001720](https://user-images.githubusercontent.com/23090085/88696343-bba75900-d135-11ea-98bf-735b9b72ccb0.png)

So you can add "Expanded" and let it automatically adjust the height to avoid errors.
![2020-07-29_005507](https://user-images.githubusercontent.com/23090085/88696714-2a84b200-d136-11ea-925c-540a3d360b71.jpg)
![Screenshot_20200729-002714](https://user-images.githubusercontent.com/23090085/88696757-35d7dd80-d136-11ea-875d-39ab0e93f544.png)

**Comment by shivanigupta19** [comment]
Please close the issue
